Repository oss-review-toolkit/ort, pull requests merged in 2021-07, with the labels that each got.

#4243 DependencyGraphConverter: Take issues of dependencies into account
  model/src/main/kotlin/utils/DependencyGraphConverter.kt
  model/src/test/kotlin/utils/DependencyGraphConverterTest.kt
Labels: bug

#4246 Stop dynamically creating issues for unmapped licenses
  model/src/main/kotlin/AnalyzerResult.kt
  model/src/main/kotlin/CuratedPackage.kt
  reporter/src/main/kotlin/model/EvaluatedModelMapper.kt
  reporter/src/main/kotlin/utils/ReportTableModelMapper.kt
Labels: release notes

#4315 Git: Synchronize authentication with JGit
  downloader/build.gradle.kts
  downloader/src/main/kotlin/vcs/Git.kt
  downloader/src/test/kotlin/vcs/GitTest.kt
Labels: downloader
