Repository oss-review-toolkit/ort, pull requests merged in 2021-03, with the labels that each got.

#3673 Pip: Normalize package name
  analyzer/src/funTest/assets/projects/external/example-python-flask-expected-output.yml
  analyzer/src/funTest/assets/projects/synthetic/pip-expected-output.yml
  analyzer/src/funTest/assets/projects/synthetic/pip-python3-expected-output.yml
  analyzer/src/funTest/assets/projects/synthetic/pipenv-expected-output.yml
  analyzer/src/funTest/assets/projects/synthetic/pipenv-python3-expected-output.yml
  analyzer/src/main/kotlin/managers/Pip.kt
  examples/curations.yml
Labels: analyzer, breaking change

#3724 AdvisorRecord: Change the type of advisorResults to a map
  advisor/src/main/kotlin/Advisor.kt
  advisor/src/test/kotlin/advisors/VulnerableCodeTest.kt
  model/src/main/kotlin/AdvisorRecord.kt
  model/src/main/kotlin/OrtResult.kt
  model/src/test/kotlin/AdvisorRecordTest.kt
  reporter/src/main/kotlin/reporters/AsciiDocTemplateReporter.kt
  reporter/src/main/resources/templates/asciidoc/vulnerability_report.ftl
Labels: breaking change

#3757 reporter-web-app: Update versions of dependencies
  reporter-web-app/package.json
  reporter-web-app/yarn.lock
Labels: javascript, reporter

#3772 advisor: Allow multiple vulnerability providers in one run
  advisor/src/main/kotlin/Advisor.kt
  cli/src/main/kotlin/commands/AdvisorCommand.kt
Labels: breaking change

#3685 Convert Provenance to a sealed class
  analyzer/src/funTest/kotlin/integration/AbstractIntegrationSpec.kt
  downloader/src/funTest/kotlin/BabelFunTest.kt
  downloader/src/funTest/kotlin/BeanUtilsFunTest.kt
  downloader/src/funTest/kotlin/DownloaderFunTest.kt
  downloader/src/main/kotlin/Downloader.kt
  evaluator/src/test/kotlin/TestData.kt
  helper-cli/src/main/kotlin/commands/GeneratePackageConfigurationsCommand.kt
  helper-cli/src/main/kotlin/commands/ListLicensesCommand.kt
  helper-cli/src/main/kotlin/commands/SubtractScanResultsCommand.kt
  helper-cli/src/main/kotlin/common/Utils.kt
  model/src/main/kotlin/Provenance.kt
  model/src/main/kotlin/ScanResult.kt
  model/src/main/kotlin/config/PackageConfiguration.kt
  model/src/main/kotlin/licenses/DefaultLicenseInfoProvider.kt
  model/src/main/kotlin/licenses/LicenseInfoResolver.kt
  model/src/main/kotlin/utils/Extensions.kt
  model/src/main/kotlin/utils/FileArchiver.kt
  model/src/main/kotlin/utils/FileArchiverFileStorage.kt
  model/src/main/kotlin/utils/FileArchiverStorage.kt
  model/src/main/kotlin/utils/PostgresFileArchiverStorage.kt
  model/src/test/kotlin/ScanResultContainerTest.kt
  model/src/test/kotlin/config/PackageConfigurationTest.kt
  model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt
  model/src/test/kotlin/licenses/TestData.kt
  model/src/test/kotlin/utils/FileArchiverTest.kt
  model/src/test/kotlin/utils/PostgresFileArchiverStorageTest.kt
  reporter/src/funTest/assets/static-html-reporter-test-input.yml
  reporter/src/funTest/kotlin/TestData.kt
  reporter/src/funTest/kotlin/reporters/SpdxDocumentReporterFunTest.kt
  reporter/src/main/kotlin/reporters/StaticHtmlReporter.kt
  reporter/src/main/kotlin/utils/FreemarkerTemplateProcessor.kt
  reporter/src/main/kotlin/utils/SpdxDocumentModelMapper.kt
  reporter/src/test/kotlin/utils/FreeMarkerTemplateProcessorTest.kt
  scanner/src/funTest/assets/file-counter-expected-output-for-analyzer-result.yml
  scanner/src/funTest/kotlin/storages/AbstractStorageFunTest.kt
  scanner/src/main/kotlin/LocalScanner.kt
  scanner/src/main/kotlin/ScanResultsStorage.kt
  scanner/src/main/kotlin/scanners/fossid/FossId.kt
  scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt
  scanner/src/test/kotlin/storages/CompositeStorageTest.kt
Labels: breaking change

#3670 pull-request-template: Replace relative link
  .github/pull_request_template.md
Labels: documentation
