Repository oss-review-toolkit/ort, pull requests merged in 2022-05, with the labels that each got.

#5295 README: Add section pointing to CONTRIBUTING.md and Slack
  README.md
Labels: documentation

#3145 Improve unmanaged file checks
  analyzer/src/main/kotlin/Analyzer.kt
Labels: analyzer, breaking change, release notes

#5362 Pip: Fix license detection for license containing separators
  analyzer/src/main/kotlin/managers/Pip.kt
Labels: release notes
