Repository oss-review-toolkit/ort, pull requests merged in 2022-03, with the labels that each got.

#5123 Add declared license mapping for "Apache-2.0 license"
  utils/spdx/src/main/resources/declared-license-mapping.yml
Labels: spdx-utils

#5147 declared-license-mapping: Map 'CDDL+GPL' entries with 'OR'
  utils/spdx/src/main/resources/declared-license-mapping.yml
Labels: release notes

#5099 Simplify vulnerability rules
  evaluator/src/main/kotlin/PackageRule.kt
  evaluator/src/test/kotlin/PackageRuleTest.kt
  examples/evaluator-rules/src/main/resources/example.rules.kts
Labels: breaking change, release notes

#5191 NPM: Upgrade to 8.5.0
  Dockerfile
  analyzer/src/main/kotlin/managers/Npm.kt
Labels: release notes
