Repository oss-review-toolkit/ort, pull requests merged in 2022-01, with the labels that each got.

#4922 JiraNotifier: Port from ORT's `Result` to Kotlin's `Result`
  notifier/src/main/kotlin/modules/JiraNotifier.kt
  notifier/src/test/kotlin/modules/JiraNotifierTest.kt
Labels: breaking change

#4916 Upgrade ScanCode to 30.1.0
  Dockerfile
  gradle.properties
  scanner/src/test/assets/scancode-output-format-1.0.0_mime-types-2.1.18.json
  scanner/src/test/kotlin/scanners/scancode/ScanCodeResultParserTest.kt
Labels: scanner, release notes

#4934 Use JDK 17 LTS in the `Dockerfile`
  Dockerfile
Labels: release notes

#5009 Dockerfile: Upgrade sbt to version 1.6.1
  Dockerfile
Labels: release notes
