Repository oss-review-toolkit/ort, pull requests merged in 2023-05, with the labels that each got.

#6962 docs(ADOPTERS): Add EPAM Systems as an adopter of ORT
  ADOPTERS.md
Labels: documentation

#6966 utils: Improve the listing of VCS directories
  utils/common/src/main/kotlin/Utils.kt
Labels: release notes

#6994 Use the term "file list" instead of "file listing"
  integrations/schemas/ort-configuration-schema.json
  model/src/main/kotlin/config/FileListStorageConfiguration.kt
  model/src/main/kotlin/config/ScannerConfiguration.kt
  model/src/main/resources/reference.yml
  model/src/test/kotlin/config/OrtConfigurationTest.kt
  scanner/src/main/kotlin/FileList.kt
  scanner/src/main/kotlin/Scanner.kt
  scanner/src/main/kotlin/utils/FileListResolver.kt
  scanner/src/test/assets/expected-file-list.yml
  scanner/src/test/kotlin/utils/FileListResolverTest.kt
Labels: scanner, breaking change, release notes, breaking configuration change

#6998 Simplify `retrievePackageFindings()`'s return value
  advisor/src/funTest/assets/retrieve-package-findings-expected-result.json
  advisor/src/funTest/kotlin/OsvFunTest.kt
  advisor/src/main/kotlin/AdviceProvider.kt
  advisor/src/main/kotlin/Advisor.kt
  advisor/src/main/kotlin/advisors/GitHubDefects.kt
  advisor/src/main/kotlin/advisors/NexusIq.kt
  advisor/src/main/kotlin/advisors/OssIndex.kt
  advisor/src/main/kotlin/advisors/Osv.kt
  advisor/src/main/kotlin/advisors/VulnerableCode.kt
  advisor/src/test/kotlin/AdvisorTest.kt
  advisor/src/test/kotlin/advisors/GitHubDefectsTest.kt
  advisor/src/test/kotlin/advisors/OssIndexTest.kt
  advisor/src/test/kotlin/advisors/VulnerableCodeTest.kt
Labels: release notes, breaking API change

#7027 refactor!: Use camel-case for URLs in function names
  plugins/reporters/opossum/src/main/kotlin/OpossumReporter.kt
  utils/ort/src/main/kotlin/OrtProxySelector.kt
  utils/ort/src/test/kotlin/OrtProxySelectorTest.kt
Labels: release notes, breaking API change

#7054 fix(FileListStorageConfiguration): Fix-up the database table name
  model/src/main/kotlin/config/FileListStorageConfiguration.kt
Labels: breaking change
