Repository oss-review-toolkit/ort, pull requests merged in 2023-10, with the labels that each got.

#7606 fix(node): Bring back NodeJS arg to local docker_build script
  scripts/docker_build.sh
Labels: bug

#7617 fix(docker): Enable build on schedule event
  .github/workflows/docker-ort-runtime-ext.yml
  .github/workflows/docker-ort-runtime.yml
Labels: bug

#7673 refactor(scanner)!: Use the configurable plugin API for scanner wrappers
  plugins/commands/requirements/src/main/kotlin/RequirementsCommand.kt
  plugins/commands/scanner/src/main/kotlin/ScannerCommand.kt
  plugins/scanners/askalono/src/funTest/kotlin/AskalonoFunTest.kt
  plugins/scanners/askalono/src/main/kotlin/Askalono.kt
  plugins/scanners/boyterlc/src/funTest/kotlin/BoyterLcFunTest.kt
  plugins/scanners/boyterlc/src/main/kotlin/BoyterLc.kt
  plugins/scanners/fossid/src/main/kotlin/FossId.kt
  plugins/scanners/fossid/src/main/kotlin/FossIdConfig.kt
  plugins/scanners/fossid/src/main/kotlin/FossIdNamingProvider.kt
  plugins/scanners/fossid/src/main/kotlin/FossIdUrlProvider.kt
  plugins/scanners/licensee/src/funTest/kotlin/LicenseeFunTest.kt
  plugins/scanners/licensee/src/main/kotlin/Licensee.kt
  plugins/scanners/scancode/src/funTest/kotlin/ScanCodeScannerFunTest.kt
  plugins/scanners/scancode/src/main/kotlin/ScanCode.kt
  plugins/scanners/scancode/src/main/kotlin/ScanCodeConfig.kt
  plugins/scanners/scancode/src/test/kotlin/ScanCodeTest.kt
  plugins/scanners/scanoss/src/main/kotlin/ScanOss.kt
  plugins/scanners/scanoss/src/main/kotlin/ScanOssConfig.kt
  plugins/scanners/scanoss/src/test/kotlin/ScanOssScannerDirectoryTest.kt
  plugins/scanners/scanoss/src/test/kotlin/ScanOssScannerFileTest.kt
  scanner/src/main/kotlin/ScannerMatcher.kt
  scanner/src/main/kotlin/ScannerWrapperFactory.kt
  scanner/src/main/kotlin/storages/ClearlyDefinedStorage.kt
  scanner/src/test/kotlin/ScannerMatcherTest.kt
Labels: breaking API change

#7719 analyzer: Support references to local modules with `GoMod`
  analyzer/src/funTest/assets/projects/synthetic/gomod-submodules-embed-expected-output.yml
  analyzer/src/funTest/kotlin/managers/GoModFunTest.kt
  analyzer/src/main/kotlin/managers/GoMod.kt
  analyzer/src/testFixtures/kotlin/Extensions.kt
Labels: enhancement, analyzer, release notes
